version: '3'
services:
  web:
    container_name: vgr-vue-ui
    image: node:18-slim
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
